- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root

  - name : Stop the http-server/container
    docker_container:
    name : insure-me
    state : stopped

  - name : Remove Existing Container
    command : docker rm insure-me

  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 sivaops7/insure-me:3.0
